clusterName: ${CLUSTER_NAME}
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-aws-loadbalancer-controller-role
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
