---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "$CLUSTER_NAME"
  region: "$REGION"
  version: "$CLUSTER_VERSION"
vpc:
  id: "$VPC_ID"
  subnets:
    private:
      private-one:
        id: "$PRIVATE_SUBNET1_ID"
      private-two:
        id: "$PRIVATE_SUBNET2_ID"
      private-three:
        id: "$PRIVATE_SUBNET3_ID"
iam:
  withOIDC: true

addons:
  - name: vpc-cni
    configurationValues: |
      {
        "env": {
          "WARM_ENI_TARGET": "2",
          "WARM_IP_TARGET": "5",
          "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG": "${AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG}",
          "ENI_CONFIG_LABEL_DEF": "${ENI_CONFIG_LABEL_DEF}"
        }
      }