controller:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-efs-csi-role
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
