controller:
  admissionWebhooks:
    patch:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
defaultBackend:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
