serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${CLUSTER_NAME}-karpenter
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
replicas: 2
settings:
  aws:
    clusterName: ${CLUSTER_NAME}
    interruptionQueueName: ${CLUSTER_NAME}
    defaultInstanceProfile: KarpenterNodeInstanceProfile-${CLUSTER_NAME}
  featureGates:
    drift: false
    