AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  These are AWS Glue ETL jobs to process the CUR data.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: EnhancedCUR
    Description: This is an ETL job to process CUR and related data to help customer to know AWS cost easily.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  CURBucketName:
    Description: The name of S3 bucket to store CUR data.
    Type: String
  WorkBucketName:
    Description: The name of S3 bucket to store the etl script and data.
    Type: String
Resources:

  CUREtlRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '-', [ !Ref 'AWS::StackName', 'CUREtlRole' ] ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess
      Policies:
        - PolicyName: "PassRoleToSession"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource: 
                  # - '*'
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/${AWS::StackName}-CUREtlRole"
        - PolicyName: "S3ReadWrite"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:*"
                Resource: 
                  - !Join [ '', [ 'arn:aws:s3:::', !Ref WorkBucketName, '/*' ] ]
        - PolicyName: "S3Read"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:Get*"
                Resource: 
                  - !Join [ '', [ 'arn:aws:s3:::', !Ref CURBucketName, '/*' ] ]
        - PolicyName: "CloudWatchLog"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: 
                  - "*"
    
  AllocateUntagJob:
    Type: AWS::Glue::Job
    Properties:
      Role: !Ref CUREtlRole
      GlueVersion: 4.0
      Command:
        Name: glueetl
        ScriptLocation: './allocate-untag.py'
      DefaultArguments:
        '--month': '2024-06'
        '--tags-fields': 'resource_tags_user_project'
        '--cur-database': 'athenacurcfn_c_u_r_athena'
        '--cur-table': 'cur_athena'
        '--work-bucket': !Ref WorkBucketName
        '--enable-glue-datacatalog': 'true'
        '--verbose': '0'

Outputs:
  AllocateUntagJob:
    Description: "Glue Job name"
    Value: !Ref AllocateUntagJob 

