  ComplianceNotifyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/ComplianceNotify/state.asl.json
      DefinitionSubstitutions:
        CheckIamUserComplianceFunctionArn: !GetAtt CheckIamUserComplianceFunction.Arn
        LoadComplianceNotifyInputFunctionArn: !GetAtt LoadComplianceNotifyInputFunction.Arn 
        NotifySnsFunctionArn: !GetAtt NotifySnsFunction.Arn
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.config
              detail-type:
                - "Config Rules Compliance Change"
              detail:
                messageType:
                  - "ComplianceChangeNotification"
                newEvaluationResult:
                  complianceType:
                    - "NON_COMPLIANT"
                configRuleName:
                  - !Ref IamComplianceConfigRule 
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadComplianceNotifyInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySnsFunction
