AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoOps contains useful operational processes represented as a state machines with AWS StepFunctions.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsSecurityHarden
    Description: A toolkit for auto ops in AWS.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  SnsTopicArn:
    Type: String
    Description: Enter SNS topic arn which notifications will send to.
Resources:
  SecurityHardenStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state.asl.json
      DefinitionSubstitutions:
        LoadSecurityHardenInputFunctionArn: !GetAtt LoadSecurityHardenInputFunction.Arn 
        NotifySnsFunctionArn: !GetAtt NotifySnsFunction.Arn
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.guardduty
              detail-type:
                - "GuardDuty Finding"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadSecurityHardenInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySnsFunction
  LoadSecurityHardenInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: LoadSecurityHardenInput
  NotifySnsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: NotifySns
      Policies: [AmazonSNSFullAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
Outputs:
  SecurityHardenStateMachineArn:
    Description: ARN of SecurityHardenStateMachine
    Value: !Ref SecurityHardenStateMachine 
