AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Transform and deliver CloudFront standard logs in S3 bucket to Amazon ElasticSearch service. 
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsRedshiftAuditLogToES 
    Description: Transform and deliver Redshift audit logs in S3 bucket to Amazon ElasticSearch service.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  BucketName:
    Type: String
    Description: Name of S3 bucket storing Redshift audit logs.
  BatchSize:
    Type: String
    Description: Number of record in a ElasticSearh bulk api call.
  ESRegion:
    Type: String
    Description: 'Enter SNS topic arn which notifications will send to. (Example: us-east-1)'
  ESEndpoint:
    Type: String
    Description: 'Enter SNS topic arn which notifications will send to. (EXample: https://es.example.com)'
Resources:
  RedshiftAuditLogTransformFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 512 
      Timeout: 300 
      Policies: 
        - S3ReadPolicy:
            BucketName: !Ref BucketName 
        - !Ref ESPostPolicy
      Environment:
        Variables:
          ESRegion: !Ref ESRegion
          ESEndpoint: !Ref ESEndpoint
          BatchSize: !Ref BatchSize
  ESPostPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      PolicyDocument: '{"Version": "2012-10-17","Statement": [{"Effect": "Allow","Action": ["es:ESHttpGet"],"Resource": ["arn:aws:es:*:*:domain/*/","arn:aws:es:*:*:domain/*/_cluster/settings","arn:aws:es:*:*:domain/*/_cat/indices"]},{"Effect": "Allow","Action": "es:ListDomainNames","Resource": "*"},{"Effect": "Allow","Action": ["es:DescribeElasticsearchDomain"],"Resource": ["arn:aws:es:*:*:domain/*"]},{"Effect": "Allow","Action": ["es:ESHttpPost","es:ESHttpGet"],"Resource": ["arn:aws:es:*:*:domain/*/_opendistro/_sql"]}]}' 

Outputs:
  LambdaExecuteRole:
    Description: "Arn of role used by lambda RedshiftAuditLogTransformFunction."
    Value: 
      !Sub
        - arn:aws:iam::${AWS::AccountId}:role/${RoleName}
        - RoleName: !Ref RedshiftAuditLogTransformFunctionRole
