  LoadEc2AlarmAutoCreatingInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/LoadEc2AlarmAutoCreatingInput