serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::597377428377:role/demo1-karpenter
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
replicas: 2
settings:
  aws:
    clusterName: demo1
    interruptionQueueName: demo1
    defaultInstanceProfile: KarpenterNodeInstanceProfile-demo1
  featureGates:
    drift: false
    