AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Format PHD events and notify users by SNS topic.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsPhdEventProcessor
    Description: Format PHD events and notify users by SNS topic.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  SnsTopicArn:
    Type: String
    Description: Enter SNS topic arn which notifications will send to.
    Default: ""
Resources:
  PhdEventProcessor:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state.asl.json
      DefinitionSubstitutions:
        LoadPhdEventProcessorInputFunctionArn: !GetAtt LoadPhdEventProcessorInputFunction.Arn
        FormatEC2MaintenanceEventFunctionArn: !GetAtt FormatEC2MaintenanceEventFunction.Arn
        FormatGeneralEventFunctionArn: !GetAtt  FormatGeneralEventFunction.Arn
        NotifySnsFunctionArn: !GetAtt NotifySnsFunction.Arn
      Events:
        HealthEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.health
              detail-type:
                - "AWS Health Event"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadPhdEventProcessorInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FormatEC2MaintenanceEventFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FormatGeneralEventFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySnsFunction

  LoadPhdEventProcessorInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: LoadPhdEventProcessorInput

  FormatEC2MaintenanceEventFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: FormatEC2MaintenanceEvent
      Policies: [AmazonEC2ReadOnlyAccess]
      Environment:
        Variables:
          RECEIVER: 'all'

  FormatGeneralEventFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: FormatGeneralEvent
      Environment:
        Variables:
          RECEIVER: 'all'

  NotifySnsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: NotifySns
      Policies: [AmazonSNSFullAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn    

Outputs:
  PhdEventProcessor:
    Description: "ARN of PhdEventProcessorStateMachine"
    Value: !Ref PhdEventProcessor
