
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Process non-compliant resource in AWS Config and send notifications.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsComplianceProcessor
    Description: Process non-compliant resource in AWS Config and send notifications.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  SnsTopicArn:
    Type: String
    Description: Enter SNS topic arn which notifications will send to.
    Default: ""
Resources:
  ComplianceProcessor:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state.asl.json
      DefinitionSubstitutions:
        CheckIamUserComplianceFunctionArn: !GetAtt CheckIamUserComplianceFunction.Arn
        LoadComplianceNotifyInputFunctionArn: !GetAtt LoadComplianceNotifyInputFunction.Arn
        FormatIamComplianceEventFunctionArn: !GetAtt FormatIamComplianceEventFunction.Arn
        NotifySnsFunctionArn: !GetAtt NotifySnsFunction.Arn
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.config
              detail-type:
                - "Config Rules Compliance Change"
              detail:
                messageType:
                  - "ComplianceChangeNotification"
                newEvaluationResult:
                  complianceType:
                    - "NON_COMPLIANT"
                configRuleName:
                  - !Ref IamUserConfigRule 
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadComplianceNotifyInputFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref FormatIamComplianceEventFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySnsFunction
    DependsOn: IamUserConfigRule 

  LoadComplianceNotifyInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: LoadComplianceNotifyInput
  
  FormatIamComplianceEventFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: FormatIamComplianceEvent
      Environment:
        Variables:
          RECEIVER: 'all'  

  NotifySnsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: NotifySns
      Policies: [AmazonSNSFullAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn   

  CheckIamUserComplianceFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: CheckIamUserCompliance
      Policies: [AWSConfigRulesExecutionRole]

  ConfigPermissionToCallLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Fn::GetAtt: 
          - CheckIamUserComplianceFunction 
          - Arn
      Action: "lambda:InvokeFunction"
      Principal: "config.amazonaws.com"

  IamUserConfigRule: 
    Type: AWS::Config::ConfigRule
    Properties: 
      InputParameters: 
        requiredGroupList: "Group1,Group2" 
        exemptedUserList: "admin,Admin" 
      Scope: 
        ComplianceResourceTypes: 
          - "AWS::IAM::User"
      Source: 
        Owner: "CUSTOM_LAMBDA"
        SourceDetails: 
          - 
            EventSource: "aws.config"
            MessageType: "ConfigurationItemChangeNotification"
          -
            EventSource: "aws.config"
            MessageType: "ScheduledNotification"
            MaximumExecutionFrequency: "TwentyFour_Hours"
        SourceIdentifier: 
          Fn::GetAtt: 
            - CheckIamUserComplianceFunction
            - Arn
    DependsOn: ConfigPermissionToCallLambda

Outputs:
  ComplianceProcessor:
    Description: "ARN of ComplianceProcessor"
    Value: !Ref ComplianceProcessor 
