AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Format auto scaling group events and notify users by SNS topic.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsASGEventProcessor
    Description: Format ASG events and notify users by SNS topic.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  SnsTopicArn:
    Type: String
    Description: Enter SNS topic arn which notifications will send to.
    Default: ""
Resources:
  ASGEventProcessor:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state.asl.yaml
      DefinitionSubstitutions:
        LoadInstancesFunctionArn: !GetAtt LoadInstancesFunction.Arn
        NotifySnsFunctionArn: !GetAtt NotifySnsFunction.Arn
      Events:
        ASGEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.autoscaling
              detail-type:
                - "EC2 Instance Launch Successful"
                - "EC2 Instance Terminate Successful"
                - "EC2 Instance Launch Unsuccessful"
                - "EC2 Instance Terminate Unsuccessful"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadInstancesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySnsFunction

  LoadInstancesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: LoadInstances
      Policies: [AmazonEC2ReadOnlyAccess]

  NotifySnsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: NotifySns
      Policies: [AmazonSNSFullAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn    

Outputs:
  ASGEventProcessor:
    Description: "ARN of ASGEventProcessorStateMachine"
    Value: !Ref ASGEventProcessor
