AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsEventRules
Parameters:
  CloudWatchAlarmTargetArn:
    Type: String
  EC2InstanceStateTargetArn:
    Type: String
  HealthEventTargetArn:
    Type: String  
Resources:
  CloudWatchAlarmRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.cloudwatch
        detail-type:
          - CloudWatch Alarm State Change
      Targets: 
        - Arn: !Ref CloudWatchAlarmTargetArn
          Id: 1
          InputTransformer: 
            InputPathsMap:
              detail-type: $.detail-type
              account: $.account
              region: $.region
              alarmName: $.detail.alarmName
              description: $.detail.configuration.description
              state: $.detail.state.value
              reason: $.detail.state.reason
            InputTemplate: '"【告警通知】<state>\n【帐号】<account>\n【区域】<region>\n【名称】<alarmName>\n【描述】<description>\n【原因】<reason>"'
  EC2InstanceStateRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-change Notification
      Targets: 
        - Arn: !Ref EC2InstanceStateTargetArn
          Id: 1
          InputTransformer: 
            InputPathsMap:
              detail-type: $.detail-type
              account: $.account
              region: $.region
              instance-id: $.detail.instance-id
              state: $.detail.state
            InputTemplate: '"【EC2实例状态变化】<state>\n【帐号】<account>\n【区域】<region>\n【实例ID】<instance-id>"'
  HealthEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern: {"source": ["aws.health"],"detail-type": ["AWS Health Event"]}
      Targets: 
        - Arn: !Ref HealthEventTargetArn
          Id: 1
          InputTransformer: 
            InputPathsMap:
              detail-type: $.detail-type
              account: $.account
              region: $.region
              eventScopeCode: $.detail.eventScopeCode
              eventTypeCategory: $.detail.eventTypeCategory
              eventTypeCode: $.detail.eventTypeCode
              eventDescription: $.detail.eventDescription[0].latestDescription
              resources: $.resource
            InputTemplate: '"【健康事件通知】<eventTypeCode>\n【帐号】<account>\n【区域】<region>\n【资源】<resources>\n【范围】<eventScopeCode>\n【描述】<eventDescription>"'


