AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Create/Delete alarms and EBS tags for EC2 instance when they are started/terminated.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsEC2Provision 
    Description: Create/Delete alarms and EBS tags for EC2 instance when they are started/terminated.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Resources:
  EC2ProvisionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state.asl.json
      DefinitionSubstitutions:
        LoadEC2ProvisionInputFunctionArn: !GetAtt LoadEC2ProvisionInputFunction.Arn
        GetInstanceDetailFunctionArn: !GetAtt GetInstanceDetailFunction.Arn
        CreateHealthCheckAlarmsFunctionArn: !GetAtt CreateHealthCheckAlarmsFunction.Arn
        DeleteEC2AlarmsFunctionArn: !GetAtt DeleteEC2AlarmsFunction.Arn
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - "EC2 Instance State-change Notification"
              detail:
                state: 
                  - running
                  - terminated
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadEC2ProvisionInputFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref GetInstanceDetailFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref CreateHealthCheckAlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DeleteEC2AlarmsFunction 
  CreateHealthCheckAlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: CreateHealthCheckAlarms
      Policies: [CloudWatchFullAccess]
  GetInstanceDetailFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: GetInstanceDetail
      Policies: [AmazonEC2ReadOnlyAccess]
  LoadEC2ProvisionInputFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: LoadEC2ProvisionInput
  DeleteEC2AlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: DeleteEC2Alarms
      Policies: [CloudWatchFullAccess]  

Outputs:
  EC2ProvisionStateMachine:
    Description: "ARN of EC2ProvisionStateMachine"
    Value: !Ref EC2ProvisionStateMachine 
