AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsAlarmProvision 
Parameters:
  SnsTopicArn:
    Type: String
    Description: Enter SNS topic arn which notifications will send to.
    Default: ""
Resources:
  AlarmProvisionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state.asl.json
      DefinitionSubstitutions:
        RemediateEC2AlarmsFunctionArn: !GetAtt RemediateEC2AlarmsFunction.Arn
        RemediateEBSAlarmsFunctionArn: !GetAtt RemediateEBSAlarmsFunction.Arn
        RemediateRDSAlarmsFunctionArn: !GetAtt RemediateRDSAlarmsFunction.Arn
        RemediateALBAlarmsFunctionArn: !GetAtt RemediateALBAlarmsFunction.Arn
        RemediateNLBAlarmsFunctionArn: !GetAtt RemediateNLBAlarmsFunction.Arn
        RemediateVPNAlarmsFunctionArn: !GetAtt RemediateVPNAlarmsFunction.Arn
        NotifySnsFunctionArn: !GetAtt NotifySnsFunction.Arn
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: "cron(0 2 * * ? *)"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref RemediateEC2AlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RemediateEBSAlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RemediateRDSAlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RemediateALBAlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RemediateNLBAlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref RemediateVPNAlarmsFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref NotifySnsFunction 
  RemediateEC2AlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: RemediateEC2Alarms
      Policies: [CloudWatchFullAccess,AmazonEC2ReadOnlyAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
  RemediateEBSAlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: RemediateEBSAlarms
      Policies: [CloudWatchFullAccess,AmazonEC2ReadOnlyAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
  RemediateRDSAlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: RemediateRDSAlarms
      Policies: [CloudWatchFullAccess,AmazonRDSReadOnlyAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
  RemediateALBAlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: RemediateALBAlarms
      Policies: [CloudWatchFullAccess,AmazonEC2ReadOnlyAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
  RemediateNLBAlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: RemediateNLBAlarms
      Policies: [CloudWatchFullAccess,AmazonEC2ReadOnlyAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
  RemediateVPNAlarmsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: RemediateVPNAlarms
      Policies: [CloudWatchFullAccess,AmazonEC2ReadOnlyAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
  NotifySnsFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      MemorySize: 128
      Timeout: 300
      CodeUri: NotifySns
      Policies: [AmazonSNSFullAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
Outputs:
  AlarmProvisionStateMachine:
    Description: "StateMachine ARN"
    Value: !Ref AlarmProvisionStateMachine 
