  GrowWindowsNtfsFunction:
    Type: 'AWS::Serverless::Function'
    Properties: 
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 15
      CodeUri: functions/GrowWindowsNtfs
      Policies: [AmazonSSMFullAccess]
      Environment:
        Variables:
          SSM_DOCNAME: !Ref GrowWindowsNtfsDoc