---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "demo-1"
  region: "ap-northeast-1"
  version: "1.25"
vpc:
  id: "vpc-0fa219345714af743"
  subnets:
    private:
      private-one:
        id: "subnet-0dfba9cbf1a243eb4"
      private-two:
        id: "subnet-053dc36a6eee2fd5d"
      private-three:
        id: "subnet-0df398e3d5080a264"
iam:
  withOIDC: true

addons:
  - name: vpc-cni
    configurationValues: |
      {
        "env": {
          "WARM_ENI_TARGET": "2",
          "WARM_IP_TARGET": "5",
          "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG": "true",
          "ENI_CONFIG_LABEL_DEF": "topology.kubernetes.io/zone"
        }
      }