---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "demo-1"
  region: "ap-northeast-1"
  version: "1.25"
managedNodeGroups:
  - name: "ng-ondemand"
    privateNetworking: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 2
    volumeSize: 100
    ssh:
      publicKeyName: "keypair-tokyo-2024"
    instanceType: "t3.medium"
    securityGroups:
      attachIDs:
        - "sg-035921483b1edde22"
    taints:
      - key: CriticalAddonsOnly
        effect: NoSchedule
    labels:
      project: svhw
    tags:
      Project: svhw