  AddEBSVolumeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      CodeUri: functions/AddEBSVolume
      Policies: [AmazonEC2FullAccess]
      Environment:
        Variables:
          SIZE: 1 
