serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::597377428377:role/demo2-karpenter
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
replicas: 2
settings:
  aws:
    clusterName: demo2
    interruptionQueueName: demo2
    defaultInstanceProfile: KarpenterNodeInstanceProfile-demo2
  featureGates:
    drift: false
    