  CertExpirationNotify:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/CertExpirationNotify/state.asl.json
      DefinitionSubstitutions:
        LoadCertExpirationNotifyInputFunctionArn: !GetAtt LoadCertExpirationNotifyInputFunction.Arn
        FormatCertMgrEventFunctionArn: !GetAtt FormatCertMgrEventFunction.Arn
        SNSTopicArn: !Ref AutoOpsSnsTopic
      Events:
        CertToExpir:
          Type: CloudWatchEvent 
          Properties:
            Pattern:
              source:
                - aws.acm 
              detail-type:
                - "ACM Certificate Approaching Expiration"
        ApiEvent:
          Type: Api
          Properties:
            Path: /cert-expire
            Method: POST
            RestApiId:
              Ref: AutoOpsApiGateway
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LoadCertExpirationNotifyInputFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref FormatCertMgrEventFunction 
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt AutoOpsSnsTopic.TopicName
