controller:
  admissionWebhooks:
    patch:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  service:
    internal:
      enabled: true
defaultBackend:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
