AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  AutoOps contains useful operational processes represented as a state machines with AWS StepFunctions.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: AutoOpsFlowNotify
    Description: Notify ops admin when step functions workflow fails.
    Author: whuaning
    SpdxLicenseId: Apache-2.0
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
Parameters:
  SnsTopicArn:
    Type: String
    Description: Enter SNS topic arn which notifications will send to.
    Default: ""
Resources:
  FlowFailedNotifyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.7
      Description: ''
      MemorySize: 128
      Timeout: 30
      Policies: [AmazonSNSFullAccess]
      Environment:
        Variables:
          SNSTopicArn: !Ref SnsTopicArn
      Events:
        FlowStateChanged:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.states
              detail-type:
                - "Step Functions Execution Status Change"
              detail:
                status:
                  - FAILED
                  - TIMED_OUT

Outputs:
  FlowFailedNotifyFunction:
    Value: !Ref FlowFailedNotifyFunction 
